version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
    - "8081:27017"
    volumes:
    - ./data/mongo:/data/db
    # We have added it here. Ensure its under the /docker-entrypoint-initdb.d
    - ./data/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro

  api:
    build: .
    restart: always
    container_name: api
    ports:
    - "8800:8800"
    depends_on:
    - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
    